SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS 
    PROMO_BOLETA,
    FUNCIONES_BOLETA,
    PRODUCTOS_BOLETA,
    BOLETA_ASIENTO,
    BOLETA,
    FUNCION,
    PELICULA_IDIOMA,
    PELICULA_FORMATO,
    ASIENTO,
    SALA,
    SOCIO,
    CINE,
    CIUDAD,
    IDIOMA,
    FORMATO,
    PRODUCTO,
    PROMO,
    PELICULA,
    GENERO,
    RESTRICCION,
    USUARIO;
SET FOREIGN_KEY_CHECKS = 1;
